"""
Django settings for care_circle project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# Lightweight .env loader (no external dependency).
# Reads KEY=VALUE lines from <BASE_DIR>/.env into os.environ when not already set.
# `.env` should NEVER be committed (see .gitignore).
# ---------------------------------------------------------------------------
def _load_dotenv():
    env_path = BASE_DIR / '.env'
    if not env_path.exists():
        return
    for line in env_path.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition('=')
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


_load_dotenv()


def _env_bool(key, default=False):
    value = os.environ.get(key)
    if value is None:
        return default
    return value.strip().lower() in ('1', 'true', 'yes', 'on')


# Quick-start development settings - unsuitable for production

# SECURITY WARNING: keep the secret key used in production secret!
# Generate a strong one for production, e.g. with:
#   python -c "import secrets; print(secrets.token_urlsafe(50))"
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-m#!l=d#08nl9aaa#c=h+eatm%0k0!m1a=w3nx3*95v@ssze0@3',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Dev: set DEBUG=1 in .env. Production: DEBUG unset/0 and set DJANGO_ALLOWED_HOSTS.
DEBUG = _env_bool('DJANGO_DEBUG', default=False)

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get(
        'DJANGO_ALLOWED_HOSTS',
        'localhost,127.0.0.1,.vercel.app',
    ).split(',') if h.strip()
]

# Origines approuvées pour la protection CSRF (formulaires POST en HTTPS).
# Nécessaire sur Vercel (https://*.vercel.app) et pour un domaine personnalisé.
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get(
        'DJANGO_CSRF_TRUSTED_ORIGINS',
        'https://*.vercel.app',
    ).split(',') if o.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'patients',
    'forum',
    'messaging',
    'appointments',
    'health_journal',
    'admin_panel',
    'audit',
    'resources',
    'notifications',
    'pages',
]

MIDDLEWARE = [
    'care_circle.middleware.SecurityHeadersMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'care_circle.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'care_circle.context_processors.user_role',
                'care_circle.context_processors.notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'care_circle.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# En production (Vercel + Neon) : la variable d'environnement DATABASE_URL
# fournie par Vercel/Neon contient une URL PostgreSQL complète, par ex. :
#   postgresql://user:password@host.neon.tech/dbname?sslmode=require
# En développement local, on retombe sur SQLite (db.sqlite3).

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

_database_url = os.environ.get('DATABASE_URL', '').strip()
if _database_url:
    import urllib.parse

    _parsed = urllib.parse.urlparse(_database_url)
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': _parsed.path.lstrip('/'),
        'USER': urllib.parse.unquote(_parsed.username or ''),
        'PASSWORD': urllib.parse.unquote(_parsed.password or ''),
        'HOST': _parsed.hostname,
        'PORT': _parsed.port or '5432',
        'CONN_MAX_AGE': 60,
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

LANGUAGES = [
    ('fr', 'Français'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'Africa/Douala'

LOGIN_REDIRECT_URL = 'home'

LOGOUT_REDIRECT_URL = 'home'

PASSWORD_RESET_TIMEOUT = 60 * 60 * 24  # 24 h: validité du lien de connexion envoyé au patient

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

# Répertoire cible de `collectstatic` — requis par Vercel pour servir les
# fichiers statiques depuis le CDN après déploiement.
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Compression/caching des fichiers statiques en production (WhiteNoise).
# Désactivé localement pour garder le comportement DEBUG simple.
WHITENOISE_USE_FINDERS = DEBUG
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage' if not DEBUG else 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# Par défaut (développement) : emails affichés dans la console.
# Pour envoyer de vrais emails, définissez dans `.env` :
#   EMAIL_USE_SMTP=1
#   EMAIL_HOST=smtp.votredomaine.com
#   EMAIL_PORT=587
#   EMAIL_HOST_USER=...
#   EMAIL_HOST_PASSWORD=...
#   EMAIL_USE_TLS=1            (ou EMAIL_USE_SSL=1 pour 465)
#   DEFAULT_FROM_EMAIL=...
# Tant qu'aucune configuration SMTP valide n'est fournie, le backend console
# est conservé afin que le développement local continue de fonctionner.
if _env_bool('EMAIL_USE_SMTP', default=False):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = _env_bool('EMAIL_USE_TLS', default=True)
    EMAIL_USE_SSL = _env_bool('EMAIL_USE_SSL', default=False)
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@carecircle.local')


# ---------------------------------------------------------------------------
# Production hardening
# ---------------------------------------------------------------------------
# Rediriger HTTP -> HTTPS et activer les en-têtes de sécurité en production.
# (À n'activer que derrière un reverse proxy / HTTPS réel.)
if not DEBUG:
    SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', default=True)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'

# Cookies : jamais accessibles au JavaScript, restreints à une même origine.
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Refus explicite de tout inline-iframe (défense en profondeur, en plus de la CSP frame-src).
X_FRAME_OPTIONS = 'DENY'


# ---------------------------------------------------------------------------
# En-têtes de sécurité supplémentaires (ajoutés par SecurityHeadersMiddleware)
# ---------------------------------------------------------------------------
SECURITY_HEADERS = {
    # Autorise l'utilisation de la page dans un même cadre uniquement.
    'X-Frame-Options': 'DENY',
    # Bloque la détection de type MIME par le navigateur.
    'X-Content-Type-Options': 'nosniff',
    # Protection XSS des anciens navigateurs.
    'X-XSS-Protection': '1; mode=block',
    # Restreint quelles fonctionnalités API les navigateurs exposent.
    'Permissions-Policy': 'geolocation=(), microphone=(), camera=(), payment=(), usb=(), battery=()',
    # Empêche le navigateur de deviner le sens (protection XSS en transparence).
    'Cross-Origin-Opener-Policy': 'same-origin',
    'Cross-Origin-Resource-Policy': 'same-origin',
}

# Sources autorisées pour la Content-Security-Policy.
# `script-src` / `script-src-attr` reçoivent automatiquement le nonce
# de la requête en plus des sources ci-dessous.
CSP_SOURCES = {
    'default-src': ["'self'"],
    # Scripts : le nonce est injecté par le middleware ; Bootstrap chargé depuis jsDelivr.
    'script-src': ["'self'", 'https://cdn.jsdelivr.net', 'https://cdnjs.cloudflare.com', 'https://fonts.googleapis.com'],
    'script-src-attr': ["'none'"],
    # Styles : Bootstrap/Font Awesome depuis CDN ; styles inline autorisés (tailwind-like inline styles du projet).
    'style-src': ["'self'", "'unsafe-inline'", 'https://cdn.jsdelivr.net', 'https://cdnjs.cloudflare.com', 'https://fonts.googleapis.com'],
    'font-src': ["'self'", 'data:', 'https://cdn.jsdelivr.net', 'https://cdnjs.cloudflare.com', 'https://fonts.gstatic.com'],
    'img-src': ["'self'", 'data:', 'https://cdn.jsdelivr.net', 'https://cdnjs.cloudflare.com'],
    'connect-src': ["'self'"],
    'frame-src': ["'none'"],
    'object-src': ["'none'"],
    'base-uri': ["'self'"],
    'form-action': ["'self'"],
}
