# Generated by Django 6.1 on 2026-08-31 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Début')),
                ('end_time', models.TimeField(verbose_name='Fin')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Réservé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Créneau de disponibilité',
                'verbose_name_plural': 'Créneaux de disponibilité',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='healthcare_provider',
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='appointments.availabilityslot'),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=100, verbose_name='Spécialité')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de licence')),
                ('clinic_name', models.CharField(blank=True, max_length=200, verbose_name='Nom du cabinet')),
                ('clinic_address', models.TextField(blank=True, verbose_name='Adresse du cabinet')),
                ('bio', models.TextField(blank=True, verbose_name='Présentation')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Honoraires')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Médecin',
                'verbose_name_plural': 'Médecins',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='appointments.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.doctor'),
        ),
    ]
