# Generated by Django 6.1 on 2026-08-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_availabilityslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_notes',
            field=models.TextField(blank=True, verbose_name='Notes de consultation'),
        ),
    ]
