# Generated by Django 6.1.1 on 2026-09-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_patient_email_appointment_patient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='credentials_sent',
            field=models.BooleanField(default=False, verbose_name='Identifiants transmis'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='credentials_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Identifiants transmis le'),
        ),
    ]
