# Generated by Django 6.1 on 2026-09-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='share_medical_record',
            field=models.BooleanField(default=False, help_text='Autorise les médecins avec qui vous avez un rendez-vous à consulter votre dossier et votre journal de santé.', verbose_name='Partager mes données médicales avec mon médecin'),
        ),
    ]
