# Generated by Django 6.1 on 2026-09-08 12:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('appointment', 'Rendez-vous'), ('message', 'Message'), ('connection', 'Connexion'), ('forum', 'Forum'), ('system', 'Système')], default='system', max_length=20)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='Lien')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lue')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Créée le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-timestamp'],
            },
        ),
    ]
